[package]
name = "oelung-lantern"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
crossterm = "0.29.0"
oelung = { path = "../oelung" }
tokio = { version = "1", features = [ "full" ] }
uuid = { version = "1.19.0", features = [ "v4" ] }

[dev-dependencies]
anyhow = "1.0.100"
